#!/usr/bin/env bash

DOCKER_REPO=docker.io/brianmay/slurm

echo "Building slurm 23.02"
docker build \
    --tag "$DOCKER_REPO:23.02" \
    --build-arg="SLURM_VER=23.02.4" \
    --build-arg="SLURM_URL=https://www.schedmd.com/downloads/latest/slurm-23.02.4.tar.bz2" \
    .
